### ISSUE TITLE
Failed unboxing of MultiDimDeviceArray object when passed as kernel argument

### ISSUE THREAD

**Issue by muellren** [NVIDIA/grcuda#10]
Passing a `MultiDimDeviceArray` object as a `pointer` argument to a kernel throws an `IllegalArgumentException` where it should unbox the underlying pointer.

```java
Value matrix = deviceArrayConstructor.execute("int", numDim1, numDim2);
Value buildKernel = context.eval("grcuda", "buildkernel");
Value kernel = buildKernel.execute(INC2D_KERNEL_SOURCE, "inc2d<int>", "pointer, sint32, sint32");
int blocks = 80;
int threadsPerBlock = 256;
kernel.execute(blocks, threadsPerBlock).execute(matrix, numDim1, numDim2);
``` 

Exception that is thrown:
```
java.lang.IllegalArgumentException: Invalid argument when executing 'com.nvidia.grcuda.gpu.ConfiguredKernel@429bffaa'(language: grcuda, type: Unknown). expected DeviceArray type Provided arguments: ['DeviceArray(elementType=INT, dims=[19,
 53], Elements=1007, size=4028 bytes, , nativeView=LittleEndianNativearrayView(startAddress=0x00007...'(language: grcuda, type: Unknown)].
        at com.oracle.truffle.polyglot.PolyglotValue.invalidExecuteArgumentType(PolyglotValue.java:601)
        at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1682)
        at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:1760)
```

**Comment by muellren** [comment]
fixed in #11
